### ISSUE TITLE
[BUG] Game doesn´t stop 

### ISSUE THREAD

**Issue by KaptainAhoibrause** [Mika-Rsbg/mini_spiel#2]
**Describe the Bug**
If you call the `Game.stop()` function in the middle of a game you get an error.

**Steps to Reproduce**
1. Start the game with `python main.py`.
2. Select "new".
3. I built an methode to test the `Game.stop()` function, that means if you press `f` you will execute the `Game.stop()` function.
4. Observe the error.

**Expected Behavior**
The game should just stop and print the line:
`"stop_message"`
Instead of that the game prints this line and after that an error occurs.

**System Information:**
- Operating System: Linux
- Python Version: 3.12

**Additional Information**
This is the error_message:
```
Traceback (most recent call last):
  File "/home/benjamin/data/projekte/python/mini_spiel/src/main.py", line 7, in <module>
    gameInteraction.request_action()
  File "/home/benjamin/data/projekte/python/mini_spiel/src/classes.py", line 100, in request_action
    Game.stop()
  File "/home/benjamin/data/projekte/python/mini_spiel/src/classes.py", line 72, in stop
    json.dump(json_data, f)
  File "/usr/lib/python3.12/json/__init__.py", line 180, in dump
    fp.write(chunk)
io.UnsupportedOperation: not writable

```

**Comment by Mika-Rsbg** [comment]
Today I created the function to stop the game.   
To reproduce the error in the latest version of the code, you now need to use the letter `s` to stop the game.  
**I'm going to work on the issue in the next few days.**

**Comment by Mika-Rsbg** [comment]
**I fixed the error!**  
The error occured because the `score.json` file was opened in read mode and not in write mode.   
**New Code:**
```python
with open("src/score.json", "w") as f:
    json.dump(json_data, f)
``` 
**Old Code:**
```python
with open("src/score.json") as f:
    json.dump(json_data, f)
``` 
**Explanation:**
By adding the "w" I made sure that the file was opened in writing mode.
